site_name: 'Grafite Packages'
site_author: Matt Lantz

# Repository
repo_name: 'Grafite Documentation'

# Copyright
copyright: 'Copyright (c) Grafite Inc'

# Documentation and theme
docs_dir: 'docs'
site_dir: '../static_websites/docs.grafite.ca'
theme:
  name: null
  custom_dir: 'theme'
  language: en
  palette:
    primary: 'grafite'
    accent: 'grey'
  features:
    - tabs
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  logo: img/logo.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/GrafiteInc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GrafiteInc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/grafite-inc

extra_css: [ 'css/extra.css' ]
extra_javascript: [ 'js/jquery.js', 'js/scripts.js', ]

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:

nav:
  - Home: index.md
  - Contributing: contributing.md
  - License: license.md
  - Scaffold:
    - Introduction: scaffold/introduction.md
    - Overview: scaffold/overview.md
    - Activity: scaffold/activity.md
    - API: scaffold/api.md
    - Billing: scaffold/billing.md
    - Invites: scaffold/invites.md
    - Notifications: scaffold/notifications.md
    - Roles & Permissions: scaffold/roles_permissions.md
    - Upgrade Guide: scaffold/upgrade.md
  - Utilities:
    - Overview: utilities/index.md
    - Form Maker: utilities/form_maker.md
    - Database: utilities/database.md
    - Helpers: utilities/helpers.md
  - Archived:
    - Overview: archived/index.md
    - Builder: archived/builder.md
    - CMS: archived/cms.md
    - Commerce: archived/commerce.md
    - CLI: archived/cli.md
    - Crypto: archived/crypto.md
    - HomeForge: archived/homeforge.md
