site_name: 'Grafite Packages'
site_author: Matt Lantz

# Repository
repo_name: 'Grafite Documentation'

# Copyright
copyright: 'Copyright (c) Grafite Inc'

# Documentation and theme
docs_dir: 'markdown'
site_dir: '../static_websites/docs.grafite.ca'
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    accent: 'grey'
  feature:
    tabs: true
  logo: 'img/logo.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra:
  social:
    - type: github-alt
      link: https://github.com/GrafiteInc
    - type: twitter
      link: https://twitter.com/GrafiteInc

extra_css: [ 'css/extra.css' ]
extra_javascript: [ 'js/jquery.js', 'js/scripts.js', ]

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Contributing: contributing.md
  - License: license.md
  - Scaffold:
    - Introduction: scaffold/introduction.md
    # - Architecture: scaffold/architecture.md
    - Upgrade Guide: scaffold/upgrade.md
    # - Core User: scaffold/user.md
    # - Activity: scaffold/activity.md
    # - Teams: scaffold/teams.md
    # - Notifications: scaffold/notifications.md
    # - Invites: scaffold/invites.md
    # - Billing: scaffold/billing.md
    # - API: scaffold/api.md
    # - Admin: scaffold/admin.md
    # - Roles & Permissions: scaffold/roles_permissions.md
  - Utilities:
    - Overview: utilities/index.md
    - Form Maker: utilities/form_maker.md
    - Database: utilities/database.md
    - Helpers: utilities/helpers.md
  - Archived:
    - Overview: archived/index.md
    - Builder: archived/builder.md
    - CMS: archived/cms.md
    - Commerce: archived/commerce.md
    - CLI: archived/cli.md
    - Crypto: archived/crypto.md
    - HomeForge: archived/homeforge.md
